PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX uri: <http://www.semanticweb.org/sameh/ontologies/2022/4/untitled-ontology-2#>

SELECT  ?studentName ?courseName ?courseCode ?instructorName
WHERE { 
?instructor a uri:Instructor.
?instructor uri:user_name ?instructorName.
?termCourse a uri:TermCourse.
?instructor uri:teaches ?termCourse.

?course a uri:Course.
?termCourse uri:teachesMaterial ?course.
?course uri:course_name ?courseName.
?course uri:code ?courseCode.

?student a uri:Student.
?student uri:studies ?termCourse.
?student uri:user_name ?studentName.

FILTER (REGEX(?courseCode, "CSE.*")). 
}

ORDER BY ASC (?studentName)
