PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#>
PREFIX owl: <http://www.w3.org/2002/07/owl#>
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX xsd: <http://www.w3.org/2001/XMLSchema#>
PREFIX uri: <http://www.semanticweb.org/sameh/ontologies/2022/4/untitled-ontology-2#>

SELECT  ?studentName ?training ?trainingStartDate ?trainingEndDate
WHERE { 
?student a uri:Student.
?student uri:user_name ?studentName.
?training a uri:Training.
?student uri:takes ?training .
?training uri:start_date ?trainingStartDate.
?training uri:end_date ?trainingEndDate.
}

